version: '2'

services:
  proxy:
    extends:
      file: common.yml
      service: proxy
    build:
      dockerfile: Dockerfile.dev 
    ports:
      - "3000:3000"
    volumes:
      - ../services/proxy/conf:/etc/nginx/conf.d
  logging_server:
    extends:
      file: "${LOGGING_SERVER_REPO}/layouts/common.yml"
      service: logging_server
